<?php
$mysqli_connection =new mysqli("localhost","root","","climate");
$sql_connection->querry("CREATE TABLE IF NOT EXISTS districts(ID INT(11) NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID),NAME VARCHAR(30) NOT NULL UNIQUE)");

$sql_connection->querry("CREATE TABLE IF NOT EXISTS members(ID INT(11) NOT NULL AUTO_INCREMENT,PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL , PASSWORD VARCHAR(100) NOT NULL, EMAIL_ADDRESS VARCHAR(20) NOT NULL UNIQUE, DISTRICTS_ID INT(11) NOT NULL,FOREIGN KEY(DISTRICTS_ID) REFERENCES districts_id)");
